// Original outline icons; no paid Iconly asset is bundled.
const paths={home:'M3 10 12 3l9 7v10a1 1 0 0 1-1 1h-5v-7H9v7H4a1 1 0 0 1-1-1Z',chart:'M4 4v16h16M8 15l4-5 4 2 4-7',plan:'M7 3v4m10-4v4M4 9h16M5 5h14a1 1 0 0 1 1 1v14H4V6a1 1 0 0 1 1-1ZM8 13h2m4 0h2m-8 4h2',phone:'M8 2h8a2 2 0 0 1 2 2v16a2 2 0 0 1-2 2H8a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2ZM10 18h4',notes:'M5 3h14v14l-4 4H5ZM8 8h8m-8 4h6m1 9v-4h4',plus:'M12 5v14M5 12h14',arrow:'M5 12h14m-5-5 5 5-5 5',clock:'M12 8v5l3 2M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0',shield:'m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6ZM8 12l3 3 5-6',book:'M3 4h7l2 2 2-2h7v15h-7l-2 2-2-2H3ZM12 6v15',exit:'M9 4H4v16h5m5-13 5 5-5 5m-6-5h11',check:'m5 12 4 4L19 6',close:'m6 6 12 12M6 18 18 6'};
export const icon=(name)=>`<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[name]??paths.book}"/></svg>`;
export const escapeHtml=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const E=escapeHtml;
const n=x=>Number.isFinite(Number(x))?new Intl.NumberFormat('tr-TR',{maximumFractionDigits:2}).format(Number(x)):'—';
const dateLabel=d=>new Intl.DateTimeFormat('tr-TR',{day:'numeric',month:'short',timeZone:'Europe/Istanbul'}).format(new Date(d.length===10?d+'T12:00:00+03:00':d));
const stateLabel={assigned:'Bekliyor',submitted:'Kontrol bekliyor',verified:'Tamamlandı',needs_revision:'Düzeltme istendi',planned:'Planlandı',scheduled:'Planlandı',present:'Katıldı',absent:'Katılmadı',excused:'İzinli'};
export function signature(exam){return exam.type+'|'+exam.subjects.map(s=>`${s.name}:${s.correct+s.wrong+s.blank}:${s.divisor}`).sort().join('|');}
export function comparable(exams,selected){return exams.filter(e=>signature(e)===signature(selected)).sort((a,b)=>a.day.localeCompare(b.day)||a.id.localeCompare(b.id));}
export function trend(exams){
 if(exams.length<2)return '<div class="empty chart-empty">Gelişimi göstermek için aynı ders dağılımında en az iki deneme gerekli.</div>';
 const values=exams.map(e=>e.net);if(!values.every(Number.isFinite))return '<p class="error">Sonuç değerleri doğrulanamadı.</p>';
 const low=Math.min(0,Math.floor(Math.min(...values)/20)*20),high=Math.max(20,Math.ceil(Math.max(...values)/20)*20),h=170,w=600;
 const y=v=>6+(h-12)-(v-low)/(high-low)*(h-12),x=i=>10+i*(w-20)/(values.length-1),zero=y(0),points=values.map((v,i)=>`${x(i)},${y(v)}`).join(' ');
 const ticks=Array.from({length:5},(_,i)=>high-(high-low)*i/4);
 return `<div class="trend" role="img" aria-label="${E(exams.map(e=>dateLabel(e.day)+': '+n(e.net)+' net').join('; '))}"><div class="axis">${ticks.map(v=>`<span>${n(v)}</span>`).join('')}</div><div class="plot"><svg viewBox="0 0 ${w} ${h}" preserveAspectRatio="none" aria-hidden="true"><defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop stop-color="#8b70e5" stop-opacity=".16"/><stop offset="1" stop-color="#8b70e5" stop-opacity="0"/></linearGradient></defs>${ticks.map(v=>`<path d="M0 ${y(v)} H600" stroke="#dedee6" stroke-dasharray="3 5" vector-effect="non-scaling-stroke"/>`).join('')}<path d="M${x(0)} ${zero} L${points.replaceAll(' ',' L')} L${x(values.length-1)} ${zero} Z" fill="url(#area)"/><polyline points="${points}" fill="none" stroke="#7755cd" stroke-width="3" vector-effect="non-scaling-stroke"/>${values.map((v,i)=>`<circle cx="${x(i)}" cy="${y(v)}" r="4" fill="#7755cd"/>`).join('')}</svg><div class="date-axis">${exams.map(e=>`<span>${dateLabel(e.day)}</span>`).join('')}</div></div></div><details class="chart-data"><summary>Grafik verilerini göster</summary><ul>${exams.map(e=>`<li>${E(e.title)} · ${dateLabel(e.day)} · <b>${n(e.net)} net</b></li>`).join('')}</ul></details>`;
}
const panel=(title,body,action='')=>`<section class="panel"><div class="panel-head"><h2>${title}</h2>${action}</div>${body}</section>`;
const empty=text=>`<div class="empty">${text}</div>`;
const tag=(state)=>`<span class="badge ${state==='verified'||state==='present'?'positive':''}">${E(stateLabel[state]??state)}</span>`;
const sorted=(items)=>[...items].sort((a,b)=>b.day.localeCompare(a.day)||b.id.localeCompare(a.id));
function summary(ctx){const {data,profile}=ctx,exams=sorted(data.exams),last=exams[0],series=last?comparable(exams,last).slice(-6):[],previous=series.length>1?series.at(-2):null,delta=previous?last.net-previous.net:null;
 const open=data.tasks.filter(t=>t.state!=='verified'),done=data.tasks.filter(t=>t.state==='verified').length;
 const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Istanbul'}).format(new Date());
 const minutes=profile.records.filter(r=>r.kind==='study'&&r.day===today).reduce((sum,r)=>sum+r.payload.value,0);
 return `<div class="overview-grid"><section class="panel score-panel"><div class="score-heading"><div><p class="eyebrow">${last?E(last.type)+' · Son deneme':'DENEME GELİŞİMİN'}</p><p class="score">${last?n(last.net):'—'}<span>net</span></p><p class="score-context">${delta!==null?`<span class="delta">${delta>0?'+':''}${n(delta)}</span> önceki benzer denemeye göre`:'Karşılaştırılabilir sonuç geldikçe gelişimin burada.'}</p></div><span class="round-icon">${icon('chart')}</span></div><h3 class="chart-title">${last?E(last.title):'İlk adım, bir sonuç.'}</h3>${trend(series)}<p class="small muted">Aynı ders dağılımı ve ceza böleni karşılaştırılır. Net, yerleştirme puanı değildir.</p></section><div class="overview-side"><section class="panel focus-card"><span class="round-icon small-icon">${icon('clock')}</span><p class="eyebrow">BUGÜNKÜ ÇALIŞMA</p><p class="metric">${minutes? n(minutes):'—'} <span>dakika</span></p><p class="muted">${minutes?'Kaydettiğin çalışma süresi.':'Bugün henüz çalışma kaydı yok.'}</p>${ctx.me.role==='student'?`<button class="primary full" data-action="record">${icon('plus')} Çalışma kaydet</button>`:`<button class="primary full" data-view="academic">${icon('book')} Çalışma kayıtları</button>`}</section><section class="panel mini-panel"><span class="round-icon small-icon">${icon('check')}</span><div><p class="eyebrow">ÖDEV DURUMU</p><p><strong>${done}</strong> / ${data.tasks.length} tamamlandı</p><p class="small muted">${open.length} kayıt açık</p></div></section></div></div><div class="two-panels">${panel('Son denemeler',exams.length?exams.slice(0,3).map(e=>`<button class="list-button" data-exam="${E(e.id)}"><span class="square-icon">${icon('book')}</span><span><strong>${E(e.title)}</strong><small>${E(e.type)} · ${dateLabel(e.day)}</small></span><b>${n(e.net)} <small>net</small></b>${icon('arrow')}</button>`).join(''):empty('Öğretmenin sonuç eklediğinde burada görünür.'),'<button class="text-button" data-view="exams">Tümünü gör '+icon('arrow')+'</button>')}${panel('Sıradaki adım',open.length?open.slice(0,3).map(t=>`<button class="list-button" data-view="plan"><span class="square-icon">${icon('plan')}</span><span><strong>${E(t.title)}</strong><small>${E(t.subject)} · ${dateLabel(t.dueDay)}</small></span>${tag(t.state)}</button>`).join(''):empty('Bekleyen ödevin yok.'),'<button class="text-button" data-view="plan">Planına git '+icon('arrow')+'</button>')}</div>`;
}
function examsView(ctx){const exams=sorted(ctx.data.exams),type=ctx.examType??exams[0]?.type??'TYT',rows=exams.filter(e=>e.type===type),selected=rows.find(e=>e.id===ctx.examId)??rows[0];
 const staff=['teacher','counselor'].includes(ctx.me.role);
 if(!selected)return panel('Deneme analizi',`<div class="filters"><label>Sınav türü<select id="examType"><option ${type==='TYT'?'selected':''}>TYT</option><option ${type==='AYT'?'selected':''}>AYT</option></select></label></div>${empty('Bu sınav türünde sonuç yok. Eksik veri sıfır net olarak gösterilmez.')}`,staff?'<button class="primary" data-action="new-exam">'+icon('plus')+' Sonuç ekle</button>':'');
 const series=comparable(exams,selected).slice(-8),denominator=selected.correct+selected.wrong+selected.blank;
 return `${panel('Deneme analizi',`<div class="filters"><label>Sınav türü<select id="examType"><option ${type==='TYT'?'selected':''}>TYT</option><option ${type==='AYT'?'selected':''}>AYT</option></select></label><label>Deneme<select id="examSelect">${rows.map(e=>`<option value="${E(e.id)}" ${e.id===selected.id?'selected':''}>${E(e.title)} · ${dateLabel(e.day)}</option>`).join('')}</select></label></div><div class="exam-metrics"><div><p>Toplam net</p><strong>${n(selected.net)}</strong></div><div><p>Doğru</p><strong>${selected.correct}</strong></div><div><p>Yanlış</p><strong>${selected.wrong}</strong></div><div><p>Boş</p><strong>${selected.blank}</strong></div></div><p class="small muted">${denominator} soru · Her ders için net = doğru − yanlış / ceza böleni.</p>${trend(series)}`,staff?'<button class="primary" data-action="new-exam">'+icon('plus')+' Sonuç ekle</button>':'')}<div class="section-heading"><h2>Ders ders, daha net.</h2><p class="muted">${E(selected.title)}</p></div><div class="subject-grid">${selected.subjects.map(s=>{const total=s.correct+s.wrong+s.blank;return `<section class="panel subject-card"><div class="panel-head"><h3>${E(s.name)}</h3><span class="square-icon">${icon('book')}</span></div><p class="subject-net">${n(s.net)} <span>net / ${total} soru</span></p><div class="answer-bar" aria-label="${s.correct} doğru, ${s.wrong} yanlış, ${s.blank} boş"><i style="width:${s.correct/total*100}%"></i><i style="width:${s.wrong/total*100}%"></i><i style="width:${s.blank/total*100}%"></i></div><div class="answer-labels"><span><b>${s.correct}</b> Doğru</span><span><b>${s.wrong}</b> Yanlış</span><span><b>${s.blank}</b> Boş</span></div><p class="small muted">Yanlış ceza böleni: ${s.divisor}</p>${s.topics?.length?`<div class="topic-list"><h4>Girilen konu notları</h4>${s.topics.map(t=>`<p>${E(t.name)} <span>${t.wrong} yanlış · ${t.blank} boş</span></p>`).join('')}<p class="small muted">Yalnızca girilen konu kayıtları; tam konu dağılımı olmayabilir.</p></div>`:''}</section>`;}).join('')}</div><p class="note">Telefon kullanımından konu eksiği veya başarı puanı çıkarılmaz. Konu analizi, öğretmenin eklediği soru/konu kayıtlarına dayanır.</p>`;
}
function planView(ctx){const staff=['teacher','counselor'].includes(ctx.me.role),student=ctx.me.role==='student';return `<div class="two-panels">${panel('Ödev & çalışma planı',ctx.data.tasks.length?ctx.data.tasks.map(t=>`<article class="task-card"><div class="panel-head"><span class="eyebrow">${E(t.subject)}</span>${tag(t.state)}</div><h3>${E(t.title)}</h3><p class="muted">${E(t.description)}</p><p class="small">${icon('plan')} Son gün: ${dateLabel(t.dueDay)}</p>${t.studentNote?`<p class="note">Teslim notu: ${E(t.studentNote)}</p>`:''}${t.reviewNote?`<p class="note">Öğretmen geri bildirimi: ${E(t.reviewNote)}</p>`:''}<div class="actions">${student&&['assigned','needs_revision'].includes(t.state)?`<button class="primary" data-task="${E(t.id)}" data-state="submitted">${icon('check')} Teslim et</button>`:''}${staff&&t.state==='submitted'?`<button class="primary" data-task="${E(t.id)}" data-state="verified">Doğrula</button><button data-task="${E(t.id)}" data-state="needs_revision">Düzeltme iste</button>`:''}</div></article>`).join(''):empty('Henüz atanmış ödev yok.'),staff?'<button class="primary" data-action="new-task">'+icon('plus')+' Ödev ata</button>':'')}${panel('Etüt takvimi',ctx.data.sessions.length?ctx.data.sessions.map(s=>`<article class="session-card"><span class="date-tile">${dateLabel(s.startsAt)}</span><div><h3>${E(s.title)}</h3><p class="small muted">${new Intl.DateTimeFormat('tr-TR',{hour:'2-digit',minute:'2-digit',timeZone:'Europe/Istanbul'}).format(new Date(s.startsAt))}–${new Intl.DateTimeFormat('tr-TR',{hour:'2-digit',minute:'2-digit',timeZone:'Europe/Istanbul'}).format(new Date(s.endsAt))} · Türkiye saati</p>${tag(s.state??'planned')}${staff?`<div class="attendance-actions">${[['present','Katıldı'],['absent','Katılmadı'],['excused','İzinli']].map(([state,label])=>`<button data-session="${E(s.id)}" data-state="${state}" ${s.state===state?'disabled':''}>${label}</button>`).join('')}</div>`:''}</div></article>`).join(''):empty('Planlanmış etüt bulunmuyor.'),staff?'<button class="primary" data-action="new-session">'+icon('plus')+' Etüt ekle</button>':'')}</div>`;}
function dialog(title,body,onSubmit){const old=document.activeElement,d=document.createElement('dialog');d.className='workflow-dialog';d.innerHTML=`<div class="panel-head"><h2>${title}</h2><button type="button" class="icon-button" aria-label="Kapat" data-close>${icon('close')}</button></div><form class="form-stack">${body}<p class="form-error" role="alert"></p><div class="actions"><button class="primary" type="submit">Kaydet</button><button type="button" data-close>Vazgeç</button></div></form>`;document.body.append(d);d.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>d.close());d.onclose=()=>{d.remove();old?.isConnected&&old.focus();};d.querySelector('form').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('[type=submit]');b.disabled=true;try{await onSubmit(new FormData(e.target),e.target);d.close();}catch(err){d.querySelector('.form-error').textContent=err.message;b.disabled=false;}};d.showModal();return d;}
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Istanbul'}).format(new Date());
const templates={TYT:[['Türkçe',40],['Matematik',40],['Sosyal Bilimler',20],['Fen Bilimleri',20]],AYT_SAY:[['Matematik',40],['Fizik',14],['Kimya',13],['Biyoloji',13]],AYT_EA:[['Matematik',40],['Türk Dili ve Edebiyatı',24],['Tarih-1',10],['Coğrafya-1',6]]};
function newExam(ctx){const clientId=crypto.randomUUID();const d=dialog('Deneme sonucu ekle',`<label>Deneme adı<input name="title" required maxlength="120" placeholder="Örn. TYT Genel Deneme 06"></label><div class="form-grid"><label>Sınav<select name="template"><option value="TYT">TYT</option><option value="AYT_SAY">AYT · Sayısal</option><option value="AYT_EA">AYT · Eşit ağırlık</option></select></label><label>Tarih<input type="date" name="day" value="${today()}" max="${today()}" required></label></div><div class="exam-inputs"></div><p class="small muted">Doğru + yanlış + boş, dersin soru sayısına eşit olmalı. Ceza böleni 4.</p>`,async f=>{const subjects=templates[f.get('template')].map(([name,capacity],i)=>({name,correct:Number(f.get('correct'+i)),wrong:Number(f.get('wrong'+i)),blank:Number(f.get('blank'+i)),divisor:4}));await ctx.api('/students/'+ctx.profile.student.id+'/exams','POST',{clientId,title:f.get('title'),type:f.get('template')==='TYT'?'TYT':'AYT',day:f.get('day'),subjects});await ctx.reload();ctx.toast('Deneme sonucu kaydedildi.');});
 const fill=()=>{d.querySelector('.exam-inputs').innerHTML=templates[d.querySelector('[name=template]').value].map(([name,q],i)=>`<fieldset><legend>${E(name)} · ${q} soru</legend><div class="score-input-row">${[['correct','Doğru',0],['wrong','Yanlış',0],['blank','Boş',q]].map(([key,label,value])=>`<label>${label}<input name="${key+i}" type="number" min="0" max="${q}" value="${value}" required></label>`).join('')}</div></fieldset>`).join('');};d.querySelector('[name=template]').onchange=fill;fill();}
export function renderAcademicView(root,view,ctx){
 if(ctx.error){root.innerHTML=panel('Veriler yüklenemedi',`<p class="error" role="alert">${E(ctx.error)}</p><button data-reload>Yeniden dene</button>`);root.querySelector('[data-reload]').onclick=ctx.reload;return;}
 if(!ctx.data){root.innerHTML=empty('Akademik kayıtlar yükleniyor…');return;}
 root.innerHTML=view==='exams'?examsView(ctx):view==='plan'?planView(ctx):summary(ctx);
 root.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>ctx.navigate(b.dataset.view));
 root.querySelectorAll('[data-exam]').forEach(b=>b.onclick=()=>ctx.navigate('exams',{examId:b.dataset.exam,examType:ctx.data.exams.find(e=>e.id===b.dataset.exam).type}));
 const type=root.querySelector('#examType');if(type)type.onchange=()=>ctx.navigate('exams',{examType:type.value,examId:null});
 const select=root.querySelector('#examSelect');if(select)select.onchange=()=>ctx.navigate('exams',{examId:select.value});
 root.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>{const action=b.dataset.action;if(action==='record')return ctx.record();if(action==='new-exam')return newExam(ctx);
 const clientId=crypto.randomUUID();if(action==='new-task')dialog('Ödev ata','<label>Başlık<input name="title" required maxlength="120"></label><label>Ders<input name="subject" required maxlength="60"></label><label>Son gün<input name="dueDay" type="date" required value="'+today()+'"></label><label>Açıklama<textarea name="description" required maxlength="2000"></textarea></label>',async f=>{await ctx.api('/students/'+ctx.profile.student.id+'/tasks','POST',{clientId,...Object.fromEntries(f)});await ctx.reload();ctx.toast('Ödev atandı.');});
 if(action==='new-session')dialog('Etüt planla','<label>Başlık<input name="title" required maxlength="120"></label><label>Başlangıç · Türkiye saati<input name="start" type="datetime-local" required></label><label>Bitiş · Türkiye saati<input name="end" type="datetime-local" required></label>',async f=>{await ctx.api('/students/'+ctx.profile.student.id+'/sessions','POST',{clientId,title:f.get('title'),startsAt:new Date(f.get('start')+':00+03:00').toISOString(),endsAt:new Date(f.get('end')+':00+03:00').toISOString()});await ctx.reload();ctx.toast('Etüt planlandı.');});});
 root.querySelectorAll('[data-task]').forEach(b=>b.onclick=()=>{const task=ctx.data.tasks.find(t=>t.id===b.dataset.task),state=b.dataset.state;dialog(state==='submitted'?'Ödevi teslim et':state==='verified'?'Teslimi doğrula':'Düzeltme iste','<label>'+ (state==='submitted'?'Teslim notun':'Geri bildirim')+'<textarea name="note" maxlength="2000" '+(state==='needs_revision'?'required':'')+'></textarea></label>',async f=>{await ctx.api('/students/'+ctx.profile.student.id+'/tasks/'+task.id+'/transition','POST',{version:task.version,state,note:f.get('note')});await ctx.reload();ctx.toast('Ödev durumu güncellendi.');});});
 root.querySelectorAll('[data-session]').forEach(b=>b.onclick=async()=>{const s=ctx.data.sessions.find(s=>s.id===b.dataset.session);b.disabled=true;try{await ctx.api('/students/'+ctx.profile.student.id+'/sessions/'+s.id+'/attendance','POST',{version:s.version,state:b.dataset.state});await ctx.reload();ctx.toast('Katılım kaydedildi.');}catch(e){b.disabled=false;ctx.toast(e.message);}});
}
