export const preview=globalThis.DESIGN_PREVIEW===true;
let csrf='';
const errors={UNAUTHENTICATED:'Oturum sona erdi. Yeniden giriş yapın.',INVALID_CREDENTIALS:'Kurum, kullanıcı kodu veya parola hatalı.',INVALID_INPUT:'Alanları kontrol edin.',CSRF_REQUIRED:'Sayfayı yenileyip yeniden deneyin.',RATE_LIMIT:'Çok fazla deneme. Bir dakika sonra tekrar deneyin.',CONSENT_REQUIRED:'Kullanım paylaşımı için onay gerekli.',CONSENT_VERSION:'İzin değişmiş. Yeniden senkronizasyon gerekli.',DAILY_CHECKIN_EXISTS:'Bu gün için bildirim zaten var.',IDEMPOTENCY_CONFLICT:'Bu kayıt farklı içerikle daha önce gönderildi.',DAILY_MINUTES_LIMIT:'Günlük çalışma toplamı 24 saati aşamaz.',STUDENT_NOT_ACTIVE:'Öğrenci hesabı henüz aktif değil.'};
const sampleStudent={id:'preview-student',name:'Örnek Ada',class_name:'12 / A',status:'active'};
const sample={student:sampleStudent,canUsage:true,consent:{enabled:1,version:1},snapshots:[{device_id:'device-1',day:'2026-09-07',quality:'limited',window_start:'2026-09-06T21:00:00Z',window_end:'2026-09-07T20:59:59Z'}],usage:[['YouTube','Video',4920,'com.google.android.youtube'],['Instagram','Sosyal medya',2580,'com.instagram.android'],['WhatsApp','İletişim',1560,'com.whatsapp'],['Khan Academy','Eğitim',1200,'org.khanacademy.android']].map(([label,category,seconds,pkg])=>({label,category,seconds,package:pkg,device_id:'device-1',day:'2026-09-07'})),records:[{kind:'study',day:'2026-09-07',payload:{subject:'Matematik',value:90},source:'Öğrenci beyanı'},{kind:'questions',day:'2026-09-07',payload:{subject:'Matematik',value:45},source:'Öğrenci beyanı'}],notes:[],limits:{usage:2000,records:300,notes:50}};
export async function api(path,method='GET',body){
 if(preview){await new Promise(r=>setTimeout(r,60));if(path==='/me')return {name:'Demo Rehberlik',role:'counselor',tenant:{name:'Cizre Örnek Akademi'}};if(path==='/students')return {students:[sampleStudent]};if(path.endsWith('/notes')){sample.notes.unshift({id:crypto.randomUUID(),body:body.body,created_at:new Date().toISOString()});return {ok:true};}if(path.startsWith('/students/'))return structuredClone(sample);return {ok:true};}
 let response;try{response=await fetch('/api/v1'+path,{method,credentials:'same-origin',headers:{'Content-Type':'application/json',...(csrf?{'X-CSRF-Token':csrf}:{})},...(body!==undefined?{body:JSON.stringify(body)}:{})});}catch{throw new Error('Sunucuya ulaşılamadı. Bağlantıyı kontrol edip tekrar deneyin.');}
 const result=await response.json();if(!response.ok){const e=new Error(errors[result.error]??'İşlem tamamlanamadı. Alanları ve yetkinizi kontrol edin.');e.status=response.status;throw e;}if(result.csrf)csrf=result.csrf;return result;
}
