export const preview=globalThis.DESIGN_PREVIEW===true;
let csrf='';
const errors={VERSION_CONFLICT:'Kayıt başka yerde değişmiş. Yenileyip tekrar deneyin.',QUESTION_TOTAL:'Doğru, yanlış ve boş toplamı dersin soru sayısına eşit olmalı.',SESSION_OVERLAP:'Bu öğrencinin aynı saatte başka etüdü var.',SESSION_NOT_STARTED:'Bu etüt için katılım henüz işaretlenemez.',UNAUTHENTICATED:'Oturum sona erdi. Yeniden giriş yapın.',INVALID_CREDENTIALS:'Kurum, kullanıcı kodu veya parola hatalı.',INVALID_INPUT:'Alanları kontrol edin.',CSRF_REQUIRED:'Sayfayı yenileyip yeniden deneyin.',RATE_LIMIT:'Çok fazla deneme. Bir dakika sonra tekrar deneyin.',CONSENT_REQUIRED:'Kullanım paylaşımı için onay gerekli.',CONSENT_VERSION:'İzin değişmiş. Yeniden senkronizasyon gerekli.',DAILY_CHECKIN_EXISTS:'Bu gün için bildirim zaten var.',IDEMPOTENCY_CONFLICT:'Bu kayıt farklı içerikle daha önce gönderildi.',DAILY_MINUTES_LIMIT:'Günlük çalışma toplamı 24 saati aşamaz.',STUDENT_NOT_ACTIVE:'Öğrenci hesabı henüz aktif değil.'};
const sampleStudent={id:'preview-student',name:'Örnek Ada',class_name:'12 / A',status:'active'};
const sample={student:sampleStudent,canUsage:true,consent:{enabled:1,version:1},snapshots:[{device_id:'device-1',day:'2026-09-07',quality:'limited',window_start:'2026-09-06T21:00:00Z',window_end:'2026-09-07T20:59:59Z'}],usage:[['YouTube','Video',4920,'com.google.android.youtube'],['Instagram','Sosyal medya',2580,'com.instagram.android'],['WhatsApp','İletişim',1560,'com.whatsapp'],['Khan Academy','Eğitim',1200,'org.khanacademy.android']].map(([label,category,seconds,pkg])=>({label,category,seconds,package:pkg,device_id:'device-1',day:'2026-09-07'})),records:[{kind:'study',day:'2026-09-07',payload:{subject:'Matematik',value:90},source:'Öğrenci beyanı'},{kind:'questions',day:'2026-09-07',payload:{subject:'Matematik',value:45},source:'Öğrenci beyanı'}],notes:[],limits:{usage:2000,records:300,notes:50}};

const courseSpec=[['Türkçe',40],['Matematik',40],['Sosyal Bilimler',20],['Fen Bilimleri',20]];
const sampleExams=[['2026-08-12',[[24,10],[17,12],[12,5],[10,6]]],['2026-08-19',[[26,8],[20,10],[13,4],[11,5]]],['2026-08-26',[[27,7],[21,9],[14,4],[12,4]]],['2026-09-02',[[28,7],[23,8],[15,3],[13,4]]],['2026-09-07',[[31,5],[25,7],[16,2],[14,3]]]].map(([day,scores],i)=>{const subjects=courseSpec.map(([name,q],j)=>({name,correct:scores[j][0],wrong:scores[j][1],blank:q-scores[j][0]-scores[j][1],divisor:4,net:scores[j][0]-scores[j][1]/4,topics:[]}));return {id:'exam-'+i,title:'TYT Genel Deneme '+String(i+1).padStart(2,'0'),type:'TYT',day,subjects,correct:subjects.reduce((n,s)=>n+s.correct,0),wrong:subjects.reduce((n,s)=>n+s.wrong,0),blank:subjects.reduce((n,s)=>n+s.blank,0),net:subjects.reduce((n,s)=>n+s.net,0)};});
const demoAcademics={exams:sampleExams,analysis:{},tasks:[{id:'task-1',title:'Problemlerde yeni bir adım',subject:'Matematik',dueDay:'2026-09-10',description:'Problemler testinden 30 soru çöz. Takıldığın soruları etüte getir.',state:'assigned',version:1,studentNote:'',reviewNote:''},{id:'task-2',title:'Paragraf rutini',subject:'Türkçe',dueDay:'2026-09-12',description:'20 paragraf sorusu ve yanlışların kısa özeti.',state:'verified',version:3,studentNote:'20 soru tamamlandı.',reviewNote:'Etütte iki soruyu birlikte değerlendirdik.'}],sessions:[{id:'session-1',title:'Matematik · Soru çözümü',startsAt:'2026-09-09T12:00:00Z',endsAt:'2026-09-09T13:00:00Z',state:'planned',version:1},{id:'session-2',title:'Haftalık rehberlik görüşmesi',startsAt:'2026-09-11T10:30:00Z',endsAt:'2026-09-11T11:00:00Z',state:'planned',version:1}]};
export async function api(path,method='GET',body){
 if(preview){await new Promise(r=>setTimeout(r,60));const role=globalThis.DESIGN_ROLE??'student';if(path==='/me')return {name:role==='student'?'Örnek Ada':'Demo '+role,role,tenant:{name:'Cizre Örnek Akademi'},student:role==='student'?{id:sampleStudent.id,status:'active'}:null};if(path==='/students')return {students:[sampleStudent]};
 if(path.endsWith('/academics'))return structuredClone(demoAcademics);
 if(path.endsWith('/transition')){const id=path.split('/').at(-2),task=demoAcademics.tasks.find(t=>t.id===id);if(task.version!==body.version)throw new Error('Kayıt değişti. Yeniden yükleyin.');task.state=body.state;task.version++;if(role==='student')task.studentNote=body.note;else task.reviewNote=body.note;return {ok:true};}
 if(path.endsWith('/attendance')){const session=demoAcademics.sessions.find(s=>s.id===path.split('/').at(-2));session.state=body.state;session.version++;return {ok:true};}
 if(path.endsWith('/tasks')&&method==='POST'){demoAcademics.tasks.unshift({...body,id:crypto.randomUUID(),state:'assigned',version:1});return {ok:true};}
 if(path.endsWith('/sessions')&&method==='POST'){demoAcademics.sessions.push({...body,id:crypto.randomUUID(),state:'planned',version:1});return {ok:true};}
 if(path.endsWith('/exams')&&method==='POST'){const subjects=body.subjects.map(s=>({...s,net:s.correct-s.wrong/s.divisor}));demoAcademics.exams.push({...body,id:crypto.randomUUID(),subjects,correct:subjects.reduce((n,s)=>n+s.correct,0),wrong:subjects.reduce((n,s)=>n+s.wrong,0),blank:subjects.reduce((n,s)=>n+s.blank,0),net:subjects.reduce((n,s)=>n+s.net,0)});return {ok:true};}
 if(path.endsWith('/notes')){sample.notes.unshift({id:crypto.randomUUID(),body:body.body,created_at:new Date().toISOString()});return {ok:true};}
 if(path.endsWith('/records')&&method==='POST'){sample.records.unshift({...body,source:'Önizleme kaydı'});return {ok:true};}
 if(path==='/consent'&&method==='POST'){sample.consent.enabled=body.enabled?1:0;if(!body.enabled){sample.snapshots=[];sample.usage=[];}return {ok:true};}
 if(path.startsWith('/students/')){const p=structuredClone(sample);p.canUsage=['student','counselor'].includes(role);if(!p.canUsage){p.usage=[];p.snapshots=[];p.consent=null;}if(role!=='counselor')p.notes=[];return p;}return {ok:true};}
 let response;try{response=await fetch('/api/v1'+path,{method,credentials:'same-origin',headers:{'Content-Type':'application/json',...(csrf?{'X-CSRF-Token':csrf}:{})},...(body!==undefined?{body:JSON.stringify(body)}:{})});}catch{throw new Error('Sunucuya ulaşılamadı. Bağlantıyı kontrol edip tekrar deneyin.');}
 const result=await response.json();if(!response.ok){const e=new Error(errors[result.error]??'İşlem tamamlanamadı. Alanları ve yetkinizi kontrol edin.');e.status=response.status;throw e;}if(result.csrf)csrf=result.csrf;return result;
}
