import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {Store,seed} from '../apps/api/src/store.ts';
import {Academics,templates,validateExam} from '../apps/api/src/academics.ts';
import {signature,comparable} from '../apps/web/academic-ui.js';
function fixture(){const s=new Store(),{ids}=seed(s),api=new Academics(s),actor=(login:string,t='cizre-demo')=>s.one('SELECT id,tenant_id,role,name FROM users WHERE id=?',ids[t+':'+login]);return {s,api,ids,actor,id:ids['cizre-demo:ogrenci:student']};}
const input=()=>({clientId:randomUUID(),title:'Test TYT',type:'TYT',day:'2026-01-01',subjects:Object.entries(templates.TYT).map(([name,q])=>({name,correct:0,wrong:q,blank:0,divisor:4}))});
function fail(fn:()=>unknown,code:string){assert.throws(fn,e=>(e as Error).message===code);}
test('normalized subject results preserve negative nets and reconcile total',()=>{const f=fixture();try{f.api.exam(f.actor('ogretmen'),f.id,input());const e=f.api.profile(f.actor('ogrenci'),f.id).exams[0];assert.equal(e.net,-30);assert.equal(e.wrong,120);assert.equal(e.subjects.length,4);}finally{f.s.close();}});
test('exam mutation allowed only for assigned academic staff',()=>{const f=fixture();try{for(const login of ['ogrenci','admin'])fail(()=>f.api.exam(f.actor(login),f.id,input()),'ACADEMIC_STAFF_ONLY');fail(()=>f.api.exam(f.actor('ogretmen'),f.ids['cizre-demo:ogrenci2:student'],input()),'NOT_FOUND');fail(()=>f.api.profile(f.actor('ogretmen','diger-demo'),f.id),'NOT_FOUND');assert.equal(f.api.exam(f.actor('rehberlik'),f.id,input()).replayed,false);}finally{f.s.close();}});
test('exam replay is canonical even if subjects reorder; changed payload conflicts',()=>{const f=fixture();try{const b=input(),one=f.api.exam(f.actor('ogretmen'),f.id,b);b.subjects.reverse();assert.deepEqual(f.api.exam(f.actor('ogretmen'),f.id,b),{id:one.id,replayed:true});b.title='Changed';fail(()=>f.api.exam(f.actor('ogretmen'),f.id,b),'IDEMPOTENCY_CONFLICT');assert.equal(f.s.one('SELECT count(*) AS n FROM exams').n,1);}finally{f.s.close();}});
test('subject capacity duplicate fields invalid dates and client-computed scores rejected',()=>{let b:any=input();b.subjects[0].correct=1;fail(()=>validateExam(b),'QUESTION_TOTAL');b=input();b.subjects[0].name='Matematik';fail(()=>validateExam(b),'DUPLICATE_SUBJECT');b=input();b.day='2026-02-30';fail(()=>validateExam(b),'INVALID_INPUT');b=input();b.subjects[0].net=100;fail(()=>validateExam(b),'UNKNOWN_FIELD');b=input();b.subjects[0].divisor=0;fail(()=>validateExam(b),'INVALID_INPUT');});
test('partial topics never exceed wrong or blank counts',()=>{const b:any=input();b.subjects[0].topics=[{name:'A',wrong:25,blank:0},{name:'B',wrong:25,blank:0}];fail(()=>validateExam(b),'TOPIC_TOTAL');b.subjects[0].topics=[{name:'A',wrong:2,blank:0}];assert.equal(validateExam(b).subjects[0].topics.length,1);});
test('AYT valid configuration accepted but unlike signatures do not mix',()=>{const b:any=input();b.type='AYT';b.subjects=Object.entries(templates.AYT_SAY).map(([name,q])=>({name,correct:q,wrong:0,blank:0,divisor:4}));assert.equal(validateExam(b).subjects.length,4);const t={...input(),id:'1'},a={...b,id:'2'};assert.notEqual(signature(t),signature(a));assert.deepEqual(comparable([t,a],t).map(e=>e.id),['1']);});
test('homework supports submit request-revision resubmit verify with optimistic locking',()=>{const f=fixture();try{const task=f.api.createTask(f.actor('ogretmen'),f.id,{clientId:randomUUID(),title:'Ödev',subject:'Matematik',dueDay:'2026-12-31',description:'Test'});f.api.transitionTask(f.actor('ogrenci'),f.id,task.id,{version:1,state:'submitted',note:'Bitti'});fail(()=>f.api.transitionTask(f.actor('ogrenci'),f.id,task.id,{version:1,state:'submitted'}),'VERSION_CONFLICT');fail(()=>f.api.transitionTask(f.actor('ogrenci'),f.id,task.id,{version:2,state:'verified'}),'INVALID_TRANSITION');fail(()=>f.api.transitionTask(f.actor('ogretmen'),f.id,task.id,{version:2,state:'needs_revision'}),'REVIEW_NOTE_REQUIRED');f.api.transitionTask(f.actor('ogretmen'),f.id,task.id,{version:2,state:'needs_revision',note:'10. soruyu tekrar ele al'});f.api.transitionTask(f.actor('ogrenci'),f.id,task.id,{version:3,state:'submitted'});f.api.transitionTask(f.actor('rehberlik'),f.id,task.id,{version:4,state:'verified'});const t=f.api.profile(f.actor('ogrenci'),f.id).tasks[0];assert.equal(t.state,'verified');assert.equal(t.version,5);}finally{f.s.close();}});
test('homework replay and cross-student target enforcement',()=>{const f=fixture();try{const b={clientId:randomUUID(),title:'A',subject:'B',description:'C',dueDay:'2026-12-01'},one=f.api.createTask(f.actor('ogretmen'),f.id,b);assert.equal(f.api.createTask(f.actor('ogretmen'),f.id,b).id,one.id);fail(()=>f.api.transitionTask(f.actor('ogrenci2'),f.id,one.id,{version:1,state:'submitted'}),'NOT_FOUND');fail(()=>f.api.transitionTask(f.actor('admin'),f.id,one.id,{version:1,state:'verified'}),'INVALID_TRANSITION');}finally{f.s.close();}});
test('sessions reject overlap, support attendance and reject stale versions',()=>{const f=fixture();try{const b={clientId:randomUUID(),title:'Etüt',startsAt:'2026-01-01T10:00:00Z',endsAt:'2026-01-01T11:00:00Z'},one=f.api.createSession(f.actor('ogretmen'),f.id,b);assert.equal(f.api.createSession(f.actor('ogretmen'),f.id,b).id,one.id);fail(()=>f.api.createSession(f.actor('ogretmen'),f.id,{...b,clientId:randomUUID()}),'SESSION_OVERLAP');fail(()=>f.api.attendance(f.actor('ogrenci'),f.id,one.id,{version:1,state:'present'}),'ACADEMIC_STAFF_ONLY');f.api.attendance(f.actor('ogretmen'),f.id,one.id,{version:1,state:'present'});fail(()=>f.api.attendance(f.actor('ogretmen'),f.id,one.id,{version:1,state:'absent'}),'VERSION_CONFLICT');assert.equal(f.api.profile(f.actor('ogrenci'),f.id).sessions[0].state,'present');}finally{f.s.close();}});
test('future attendance cannot pretend a planned session happened',()=>{const f=fixture();try{const one=f.api.createSession(f.actor('ogretmen'),f.id,{clientId:randomUUID(),title:'Future',startsAt:'2090-01-01T10:00:00Z',endsAt:'2090-01-01T11:00:00Z'});fail(()=>f.api.attendance(f.actor('ogretmen'),f.id,one.id,{version:1,state:'present'}),'SESSION_NOT_STARTED');}finally{f.s.close();}});
test('pending student and other-tenant student cannot read academics',()=>{const f=fixture();try{fail(()=>f.api.profile(f.actor('bekleyen'),f.ids['cizre-demo:bekleyen:student']),'STUDENT_NOT_ACTIVE');fail(()=>f.api.profile(f.actor('ogrenci','diger-demo'),f.id),'NOT_FOUND');}finally{f.s.close();}});
