import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {resolve} from 'node:path';
import {Store,seed} from '../apps/api/src/store.ts';
import {Academics,seedAcademics} from '../apps/api/src/academics.ts';
import {app} from '../apps/api/src/server.ts';
const db=new Store(),fixture=seed(db),academic=new Academics(db);seedAcademics(academic,db,fixture.ids);
const server=app(db);await new Promise(r=>server.listen(3100,'127.0.0.1',r));
const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{})});
const page=await browser.newPage({viewport:{width:1440,height:1050}}),errors=[],checks=[];
page.on('pageerror',e=>errors.push(e.message));
const output=resolve(process.env.QA_OUTPUT??'.local/qa-v2'),css=readFileSync(new URL('../apps/web/style.css',import.meta.url),'utf8');mkdirSync(output,{recursive:true});
async function snap(name){assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,name+' horizontal overflow');const html=await page.evaluate(css=>{const copy=document.documentElement.cloneNode(true),live=[...document.querySelectorAll('input,textarea,select')],clones=[...copy.querySelectorAll('input,textarea,select')];clones.forEach((node,i)=>{const original=live[i];if(node.tagName==='INPUT'){node.setAttribute('value',original.type==='password'?'':original.value);if(original.checked)node.setAttribute('checked','');else node.removeAttribute('checked');}else if(node.tagName==='TEXTAREA')node.textContent=original.value;else [...node.options].forEach((o,j)=>{if(original.options[j].selected)o.setAttribute('selected','');else o.removeAttribute('selected');});});copy.querySelectorAll('script,link').forEach(n=>n.remove());const style=document.createElement('style');style.textContent=css;copy.querySelector('head').append(style);const script=document.createElement('script');script.textContent="document.querySelectorAll('dialog[open]').forEach(d=>{d.removeAttribute('open');d.showModal();});";copy.querySelector('body').append(script);return '<!doctype html>'+copy.outerHTML;},css);writeFileSync(resolve(output,name+'.html'),html);}
async function login(login){await page.context().clearCookies();await page.goto('http://127.0.0.1:3100');const c=fixture.credentials.find(x=>x.tenant==='cizre-demo'&&x.login===login);await page.locator('[name=login]').fill(c.login);await page.locator('[name=password]').fill(c.password);await page.locator('#login button').click();await page.locator('#section').waitFor();}
async function nav(name){await page.locator(`[data-tab="${name}"]`).click();}
try{
 await page.goto('http://127.0.0.1:3100');await page.locator('#login').waitFor();await snap('login');
 await login('ogrenci');assert.equal(await page.locator('.score').textContent(),'81,75net');await snap('overview');
 await page.setViewportSize({width:390,height:844});await snap('overview-mobile');
 await nav('exams');assert.equal(await page.locator('.subject-card').count(),4);assert.equal(await page.locator('.exam-metrics strong').first().textContent(),'81,75');await snap('exams-mobile');
 await page.locator('#examType').selectOption('AYT');assert.ok((await page.locator('#section').textContent()).includes('Bu sınav türünde sonuç yok'));await snap('empty-mobile');
 await nav('plan');await snap('plan-mobile');await page.locator('[data-task]').first().click();await page.locator('dialog textarea').fill('Çözdüm <img src=x onerror=alert(1)>');await page.locator('dialog [type=submit]').click();await page.locator('dialog').waitFor({state:'detached'});assert.ok((await page.locator('#section').textContent()).includes('Kontrol bekliyor'));assert.equal(await page.locator('#section img').count(),0);checks.push('student subject analysis, type separation, homework submit');
 await nav('usage');assert.equal(await page.locator('.app-row').count(),4);await page.locator('#category').selectOption({label:'Eğitim'});assert.equal(await page.locator('.app-row').count(),1);await snap('usage-mobile');await page.locator('#privacy').click();await page.locator('dialog').waitFor();await page.keyboard.press('Escape');await page.locator('dialog').waitFor({state:'detached'});checks.push('privacy dialog, filtered usage');
 await page.locator('[data-tab=add]').click();await page.locator('[name=value]').fill('25');await page.locator('#newRecord button.primary').click();await page.locator('#newRecord').waitFor({state:'detached'});await nav('overview');assert.ok((await page.locator('.focus-card').textContent()).includes('100'));checks.push('study persistence and dashboard refresh');
 await page.setViewportSize({width:1440,height:1050});await login('ogretmen');assert.equal(await page.locator('[data-tab=usage]').count(),0);await nav('plan');await page.locator('[data-state=verified]').first().click();await page.locator('dialog textarea').fill('Kontrol edildi.');await page.locator('dialog [type=submit]').click();await page.locator('dialog').waitFor({state:'detached'});assert.ok((await page.locator('#section').textContent()).includes('Tamamlandı'));checks.push('teacher review, no phone access');
 await nav('exams');await page.locator('[data-action=new-exam]').click();await page.locator('dialog [name=title]').fill('QA Deneme');await snap('exam-form');await page.locator('dialog [name=correct0]').fill('1');await page.locator('dialog [type=submit]').click();await page.locator('.form-error').filter({hasText:'toplamı'}).waitFor();await snap('exam-error');await page.locator('dialog [name=blank0]').fill('39');await page.locator('dialog [type=submit]').click();await page.locator('dialog').waitFor({state:'detached'});assert.ok((await page.locator('#examSelect').textContent()).includes('QA Deneme'));checks.push('exam capacity error and persistent create');
 await nav('plan');await page.locator('[data-action=new-session]').click();await page.locator('dialog [name=title]').fill('QA Etüt');await page.locator('dialog [name=start]').fill('2026-01-01T10:00');await page.locator('dialog [name=end]').fill('2026-01-01T11:00');await page.locator('dialog [type=submit]').click();await page.locator('dialog').waitFor({state:'detached'});const event=page.locator('.session-card').filter({hasText:'QA Etüt'});await event.locator('[data-state=present]').click();await page.waitForFunction(()=>[...document.querySelectorAll('.session-card')].some(e=>e.textContent.includes('QA Etüt')&&e.querySelector('.badge')?.textContent==='Katıldı'));checks.push('session creation and attendance');
 await login('rehberlik');await nav('notes');await page.locator('textarea').fill('Sentetik görüşme <img src=x onerror=alert(1)>');await page.locator('#noteForm button').click();await page.waitForFunction(()=>document.querySelector('.record')?.textContent.includes('Sentetik görüşme'));assert.equal(await page.locator('#section img').count(),0);await snap('notes');checks.push('counselor note escaping');
 await login('admin');await page.locator('.student-chip').filter({hasText:'Örnek Ekin'}).click();await page.locator('#approve').waitFor();await snap('admin');const choices=await page.locator('.student-chip').evaluateAll(es=>es.map(e=>({id:e.dataset.id,name:e.textContent}))),ada=choices.find(x=>x.name.includes('Ada')),deniz=choices.find(x=>x.name.includes('Deniz'));await page.route('**/api/v1/students/*',async route=>{if(route.request().url().endsWith(ada.id))await new Promise(r=>setTimeout(r,400));await route.continue();});await page.locator(`[data-id="${ada.id}"]`).click();await page.locator(`[data-id="${deniz.id}"]`).click();await page.waitForTimeout(650);assert.equal(await page.locator('#content .person h2').textContent(),'Örnek Deniz');assert.equal(await page.locator('.avatar').textContent(),'ÖD');checks.push('approval screen and delayed profile race');
 assert.deepEqual(errors,[]);writeFileSync(resolve(output,'results.json'),JSON.stringify({passed:true,checks},null,2));console.log('Browser MVP checks passed:',checks.join('; '));
}finally{await browser.close();await new Promise(r=>server.close(r));db.close();}
