import {test,before,after} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {Store,seed,sha} from '../apps/api/src/store.ts';
import {day,validateBatch} from '../apps/api/src/domain.ts';
let db:Store,data:any,student:any,counselor:any,teacher:any,admin:any,other:any,sid:string;
before(()=>{db=new Store();data=seed(db,'test-only-not-a-production-secret');const actor=(key:string)=>db.one('SELECT * FROM users WHERE id=?',data.ids[key]);student=actor('cizre-demo:ogrenci');counselor=actor('cizre-demo:rehberlik');teacher=actor('cizre-demo:ogretmen');admin=actor('cizre-demo:admin');other=actor('diger-demo:rehberlik');sid=data.ids['cizre-demo:ogrenci:student'];});
after(()=>db.close());
const fail=(fn:()=>unknown,code:string)=>assert.throws(fn,(e:any)=>e.message===code);
function batch(overrides:any={}){const snap=db.one('SELECT * FROM snapshots WHERE student_id=? ORDER BY day DESC LIMIT 1',sid);return {batchId:randomUUID(),deviceId:data.ids.device,consentVersion:1,day:snap.day,revision:snap.revision+1,windowStart:snap.window_start,windowEnd:snap.window_end,timezone:'Europe/Istanbul',quality:'limited',apps:[{packageName:'com.google.android.youtube',seconds:600}],...overrides};}
test('timezone is Istanbul at UTC day boundary',()=>assert.equal(day(new Date('2026-09-07T22:30:00Z')),'2026-09-08'));
test('assigned counselor can see application category sorted by duration',()=>{const p=db.profile(counselor,sid);assert.equal(p.usage[0].category,'Video');assert.equal(p.usage[0].label,'YouTube');assert.ok(p.usage[0].seconds>=p.usage[1].seconds);});
test('other tenant cannot access profile',()=>fail(()=>db.profile(other,sid),'NOT_FOUND'));
test('same tenant unassigned student is denied',()=>fail(()=>db.profile(counselor,data.ids['cizre-demo:ogrenci2:student']),'NOT_FOUND'));
test('student cannot access peer profile',()=>fail(()=>db.profile(student,data.ids['cizre-demo:ogrenci2:student']),'NOT_FOUND'));
test('teacher sees neither telemetry nor private notes',()=>{db.note(counselor,sid,'Sentetik takip notu');const p=db.profile(teacher,sid);assert.deepEqual(p.usage,[]);assert.deepEqual(p.notes,[]);assert.equal(p.canUsage,false);});
test('admin does not get telemetry or notes',()=>{const p=db.profile(admin,sid);assert.deepEqual(p.usage,[]);assert.deepEqual(p.notes,[]);});
test('teacher cannot write guidance notes',()=>fail(()=>db.note(teacher,sid,'x'),'FORBIDDEN'));
test('assignment list does not reveal unassigned students',()=>assert.equal(db.list(counselor).length,1));
test('pending student cannot read own academics',()=>{const a=db.one('SELECT * FROM users WHERE id=?',data.ids['cizre-demo:bekleyen']);fail(()=>db.profile(a,data.ids['cizre-demo:bekleyen:student']),'STUDENT_NOT_ACTIVE');});
test('admin approval is audited and cannot be repeated',()=>{const id=data.ids['cizre-demo:bekleyen:student'];db.approve(admin,id);fail(()=>db.approve(admin,id),'INVALID_TRANSITION');assert.equal(db.one('SELECT count(*) n FROM audit WHERE action=? AND subject=?','student.approved',id).n,1);});
test('student record idempotency prevents duplicates',()=>{const b={clientRecordId:randomUUID(),kind:'study',day:day(),payload:{subject:'Türkçe',value:30}};const first=db.record(student,sid,b),again=db.record(student,sid,b);assert.equal(first.id,again.id);assert.equal(again.replayed,true);fail(()=>db.record(student,sid,{...b,payload:{subject:'Türkçe',value:31}}),'IDEMPOTENCY_CONFLICT');});
test('student cannot forge teacher exam',()=>fail(()=>db.record(student,sid,{clientRecordId:randomUUID(),kind:'exam',day:day(),payload:{}}),'FORBIDDEN_KIND'));
test('exam net uses explicit penalty divisor',()=>{db.record(teacher,sid,{clientRecordId:randomUUID(),kind:'exam',day:day(),payload:{title:'Test',correct:10,wrong:6,blank:4,divisor:3}});assert.equal(db.profile(teacher,sid).records.find((r:any)=>r.kind==='exam').payload.net,8);});
test('daily checkin only once',()=>{db.record(student,sid,{clientRecordId:randomUUID(),kind:'checkin',day:day(),payload:{state:'partial'}});fail(()=>db.record(student,sid,{clientRecordId:randomUUID(),kind:'checkin',day:day(),payload:{state:'completed'}}),'DAILY_CHECKIN_EXISTS');});
test('unknown fields cannot inject tenant or category',()=>{fail(()=>validateBatch({...batch(),tenant_id:'tenant-b'}),'UNKNOWN_FIELD');fail(()=>validateBatch(batch({apps:[{packageName:'com.test.app',seconds:60,category:'Eğitim'}]})),'UNKNOWN_FIELD');});
test('invalid, future or overflowing measurements rejected',()=>{fail(()=>validateBatch(batch({apps:[{packageName:'com.test.app',seconds:-1}]})),'INVALID_INPUT');fail(()=>validateBatch(batch({windowEnd:'2099-01-01T00:00:00Z'})),'INVALID_INPUT');fail(()=>validateBatch(batch({apps:[{packageName:'a.app',seconds:86400}]})),'DURATION_EXCEEDS_WINDOW');});
test('duplicate package rows rejected',()=>fail(()=>validateBatch(batch({apps:[{packageName:'a.app',seconds:1},{packageName:'a.app',seconds:2}]})),'DUPLICATE_PACKAGE'));
test('cross-tenant device is rejected',()=>fail(()=>db.batch(student,batch({deviceId:randomUUID()})),'DEVICE_NOT_FOUND'));
test('old consent version rejected',()=>fail(()=>db.batch(student,batch({consentVersion:99})),'CONSENT_VERSION'));
test('telemetry batch retries do not double count',()=>{const b=batch();db.batch(student,b);assert.equal(db.batch(student,b).replayed,true);assert.equal(db.profile(counselor,sid).usage.length,1);assert.equal(db.profile(counselor,sid).usage[0].seconds,600);fail(()=>db.batch(student,{...b,apps:[{packageName:'com.google.android.youtube',seconds:601}]}),'IDEMPOTENCY_CONFLICT');});
test('new snapshot replaces old duration rather than adds',()=>{db.batch(student,batch({apps:[{packageName:'unknown.application',seconds:900}]}));const r=db.profile(counselor,sid).usage[0];assert.equal(r.seconds,900);assert.equal(r.category,'Diğer / sınıflandırılmamış');});
test('stale snapshots rejected',()=>fail(()=>db.batch(student,batch({revision:1})),'STALE_SNAPSHOT'));
test('database composite FK rejects cross-tenant assignment',()=>assert.throws(()=>db.run('INSERT INTO assignments VALUES(?,?,?)','tenant-b',other.id,sid),/FOREIGN KEY/));
test('sessions store hashes not bearer tokens; logout invalidates',()=>{const r=db.login('cizre-demo','ogrenci','test-only-not-a-production-secret');assert.ok(db.one('SELECT * FROM sessions WHERE token_hash=?',sha(r.token)));assert.equal(db.one('SELECT * FROM sessions WHERE token_hash=?',r.token),undefined);assert.equal(db.session(r.token).id,student.id);db.logout(r.token);fail(()=>db.session(r.token),'UNAUTHENTICATED');});
test('wrong credential gives generic failure',()=>fail(()=>db.login('cizre-demo','missing','wrong'),'INVALID_CREDENTIALS'));
test('audit contains metadata, not sensitive note or app payload',()=>{const all=JSON.stringify(db.all('SELECT * FROM audit'));assert.ok(!all.includes('Sentetik takip notu'));assert.ok(!all.includes('com.google.android.youtube'));});
test('teacher cannot grant student consent',()=>fail(()=>db.consent(teacher,{enabled:true,noticeVersion:'2026-09-v1'}),'STUDENT_ONLY'));
test('revocation clears stored usage and blocks replay',()=>{const b=batch();const c=db.consent(student,{enabled:false,noticeVersion:'2026-09-v1'});assert.equal(c.version,2);assert.equal(db.profile(counselor,sid).usage.length,0);assert.equal(db.profile(counselor,sid).snapshots.length,0);fail(()=>db.batch(student,b),'CONSENT_REQUIRED');});
test('no production boot with development adapter',()=>{const old=process.env.NODE_ENV;process.env.NODE_ENV='production';try{fail(()=>new Store(),'DEVELOPMENT_ONLY');}finally{if(old===undefined)delete process.env.NODE_ENV;else process.env.NODE_ENV=old;}});
