import {randomUUID} from 'node:crypto';
import {check,keys,str,num,uuid,day} from './domain.ts';
import {sha} from './store.ts';
import type {Store} from './store.ts';
import type {Actor} from './domain.ts';
export const templates={TYT:{'Türkçe':40,'Matematik':40,'Sosyal Bilimler':20,'Fen Bilimleri':20},AYT_SAY:{'Matematik':40,'Fizik':14,'Kimya':13,'Biyoloji':13},AYT_EA:{'Matematik':40,'Türk Dili ve Edebiyatı':24,'Tarih-1':10,'Coğrafya-1':6}};
function validDay(value:any,future=false){check(typeof value==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(value));const d=new Date(value+'T12:00:00Z');check(Number.isFinite(d.getTime())&&d.toISOString().slice(0,10)===value&&value>='2020-01-01'&&(future||value<=day()));return value;}
export function validateExam(b:any){keys(b,['clientId','title','type','day','subjects']);check(uuid(b.clientId));check(['TYT','AYT'].includes(b.type));validDay(b.day);check(Array.isArray(b.subjects)&&b.subjects.length===4);const names=b.subjects.map((s:any)=>s.name);check(new Set(names).size===4,422,'DUPLICATE_SUBJECT');const template=Object.entries(templates).find(([key,t])=>(b.type==='TYT'?key==='TYT':key.startsWith('AYT'))&&Object.keys(t).every(name=>names.includes(name)))?.[1];check(template,422,'SUBJECT_CONFIGURATION');
 const subjects=Object.entries(template).map(([name,count])=>{const s=b.subjects.find((s:any)=>s.name===name);keys(s,['name','correct','wrong','blank','divisor','topics']);const correct=num(s.correct,0,count),wrong=num(s.wrong,0,count),blank=num(s.blank,0,count),divisor=num(s.divisor,1,10);check(correct+wrong+blank===count,422,'QUESTION_TOTAL');const topics=s.topics??[];check(Array.isArray(topics)&&topics.length<=30);const parsed=topics.map((t:any)=>{keys(t,['name','wrong','blank']);return {name:str(t.name,80),wrong:num(t.wrong,0,wrong),blank:num(t.blank,0,blank)};});check(new Set(parsed.map((t:any)=>t.name.toLocaleLowerCase('tr'))).size===parsed.length,422,'DUPLICATE_TOPIC');check(parsed.reduce((n:number,t:any)=>n+t.wrong,0)<=wrong&&parsed.reduce((n:number,t:any)=>n+t.blank,0)<=blank,422,'TOPIC_TOTAL');return {name,correct,wrong,blank,divisor,topics:parsed};});return {clientId:b.clientId,title:str(b.title),type:b.type,day:b.day,subjects};}
const note=(v:any)=>v===undefined||v===''?'':str(v,2000);
export class Academics{
 s:Store;
 constructor(store:Store){this.s=store;store.db.exec(`
 CREATE TABLE IF NOT EXISTS exams(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,student_id TEXT NOT NULL,actor_id TEXT NOT NULL,client_id TEXT NOT NULL,fingerprint TEXT NOT NULL,title TEXT NOT NULL,type TEXT NOT NULL,day TEXT NOT NULL,UNIQUE(tenant_id,student_id,id),UNIQUE(tenant_id,actor_id,client_id),FOREIGN KEY(tenant_id,student_id) REFERENCES students(tenant_id,id),FOREIGN KEY(tenant_id,actor_id) REFERENCES users(tenant_id,id));
 CREATE TABLE IF NOT EXISTS exam_subjects(tenant_id TEXT NOT NULL,student_id TEXT NOT NULL,exam_id TEXT NOT NULL,position INTEGER NOT NULL,name TEXT NOT NULL,correct INTEGER NOT NULL CHECK(correct>=0),wrong INTEGER NOT NULL CHECK(wrong>=0),blank INTEGER NOT NULL CHECK(blank>=0),divisor INTEGER NOT NULL CHECK(divisor BETWEEN 1 AND 10),topics TEXT NOT NULL,PRIMARY KEY(tenant_id,exam_id,name),FOREIGN KEY(tenant_id,student_id,exam_id) REFERENCES exams(tenant_id,student_id,id) ON DELETE CASCADE);
 CREATE TABLE IF NOT EXISTS academic_tasks(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,student_id TEXT NOT NULL,actor_id TEXT NOT NULL,client_id TEXT NOT NULL,fingerprint TEXT NOT NULL,title TEXT NOT NULL,subject TEXT NOT NULL,due_day TEXT NOT NULL,description TEXT NOT NULL,state TEXT NOT NULL DEFAULT 'assigned' CHECK(state IN ('assigned','submitted','verified','needs_revision')),version INTEGER NOT NULL DEFAULT 1,student_note TEXT NOT NULL DEFAULT '',review_note TEXT NOT NULL DEFAULT '',UNIQUE(tenant_id,actor_id,client_id),FOREIGN KEY(tenant_id,student_id) REFERENCES students(tenant_id,id),FOREIGN KEY(tenant_id,actor_id) REFERENCES users(tenant_id,id));
 CREATE TABLE IF NOT EXISTS study_sessions(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,student_id TEXT NOT NULL,actor_id TEXT NOT NULL,client_id TEXT NOT NULL,fingerprint TEXT NOT NULL,title TEXT NOT NULL,starts_at TEXT NOT NULL,ends_at TEXT NOT NULL,state TEXT NOT NULL DEFAULT 'planned' CHECK(state IN ('planned','present','absent','excused')),version INTEGER NOT NULL DEFAULT 1,UNIQUE(tenant_id,actor_id,client_id),FOREIGN KEY(tenant_id,student_id) REFERENCES students(tenant_id,id),FOREIGN KEY(tenant_id,actor_id) REFERENCES users(tenant_id,id));
 CREATE INDEX IF NOT EXISTS exams_scope ON exams(tenant_id,student_id,day);
 CREATE INDEX IF NOT EXISTS tasks_scope ON academic_tasks(tenant_id,student_id,due_day);
 CREATE INDEX IF NOT EXISTS sessions_scope ON study_sessions(tenant_id,student_id,starts_at);`);}
 staff(a:Actor,id:string){this.s.authorize(a,id);check(['teacher','counselor'].includes(a.role),403,'ACADEMIC_STAFF_ONLY');}
 replay(table:string,a:Actor,clientId:string,fingerprint:string){const old=this.s.one(`SELECT id,fingerprint FROM ${table} WHERE tenant_id=? AND actor_id=? AND client_id=?`,a.tenant_id,a.id,clientId);if(old){check(old.fingerprint===fingerprint,409,'IDEMPOTENCY_CONFLICT');return {id:old.id,replayed:true};}return null;}
 exam(a:Actor,id:string,input:any){this.staff(a,id);const b=validateExam(input),fingerprint=sha(JSON.stringify({student:id,...b}));return this.s.tx(()=>{const old=this.replay('exams',a,b.clientId,fingerprint);if(old)return old;const key=randomUUID();this.s.run('INSERT INTO exams VALUES(?,?,?,?,?,?,?,?,?)',key,a.tenant_id,id,a.id,b.clientId,fingerprint,b.title,b.type,b.day);b.subjects.forEach((s,i)=>this.s.run('INSERT INTO exam_subjects VALUES(?,?,?,?,?,?,?,?,?,?)',a.tenant_id,id,key,i,s.name,s.correct,s.wrong,s.blank,s.divisor,JSON.stringify(s.topics)));this.s.audit(a,'exam.created',key);return {id:key,replayed:false};});}
 profile(a:Actor,id:string){this.s.authorize(a,id);const exams=this.s.all('SELECT id,title,type,day FROM exams WHERE tenant_id=? AND student_id=? ORDER BY day,id LIMIT 500',a.tenant_id,id).map(e=>{const subjects=this.s.all('SELECT name,correct,wrong,blank,divisor,topics FROM exam_subjects WHERE tenant_id=? AND student_id=? AND exam_id=? ORDER BY position',a.tenant_id,id,e.id).map(s=>({...s,topics:JSON.parse(s.topics),net:Math.round((s.correct-s.wrong/s.divisor)*100)/100}));return {...e,subjects,correct:subjects.reduce((n,s)=>n+s.correct,0),wrong:subjects.reduce((n,s)=>n+s.wrong,0),blank:subjects.reduce((n,s)=>n+s.blank,0),net:Math.round(subjects.reduce((n,s)=>n+s.net,0)*100)/100};});const tasks=this.s.all('SELECT id,title,subject,due_day AS dueDay,description,state,version,student_note AS studentNote,review_note AS reviewNote FROM academic_tasks WHERE tenant_id=? AND student_id=? ORDER BY due_day,id LIMIT 500',a.tenant_id,id);const sessions=this.s.all('SELECT id,title,starts_at AS startsAt,ends_at AS endsAt,state,version FROM study_sessions WHERE tenant_id=? AND student_id=? ORDER BY starts_at,id LIMIT 500',a.tenant_id,id);this.s.audit(a,'academics.read',id);return {exams,tasks,sessions,analysis:{method:'Separate exam type + subject configuration + divisor; no placement-score inference'},limits:{exams:500,tasks:500,sessions:500}};}
 createTask(a:Actor,id:string,b:any){this.staff(a,id);keys(b,['clientId','title','subject','dueDay','description']);check(uuid(b.clientId));const data={title:str(b.title),subject:str(b.subject,60),dueDay:validDay(b.dueDay,true),description:str(b.description,2000)},fingerprint=sha(JSON.stringify({student:id,...data}));return this.s.tx(()=>{const old=this.replay('academic_tasks',a,b.clientId,fingerprint);if(old)return old;const key=randomUUID();this.s.run('INSERT INTO academic_tasks(id,tenant_id,student_id,actor_id,client_id,fingerprint,title,subject,due_day,description) VALUES(?,?,?,?,?,?,?,?,?,?)',key,a.tenant_id,id,a.id,b.clientId,fingerprint,data.title,data.subject,data.dueDay,data.description);this.s.audit(a,'task.assigned',key);return {id:key,replayed:false};});}
 transitionTask(a:Actor,id:string,taskId:string,b:any){this.s.authorize(a,id);keys(b,['version','state','note']);num(b.version,1,2147483647);const body=note(b.note);return this.s.tx(()=>{const t=this.s.one('SELECT state,version FROM academic_tasks WHERE tenant_id=? AND student_id=? AND id=?',a.tenant_id,id,taskId);check(t,404,'NOT_FOUND');check(t.version===b.version,409,'VERSION_CONFLICT');const student=a.role==='student';check(student?(['assigned','needs_revision'].includes(t.state)&&b.state==='submitted'):(['teacher','counselor'].includes(a.role)&&t.state==='submitted'&&['verified','needs_revision'].includes(b.state)),403,'INVALID_TRANSITION');if(b.state==='needs_revision')check(body.length>0,422,'REVIEW_NOTE_REQUIRED');this.s.run(`UPDATE academic_tasks SET state=?,version=version+1,${student?'student_note':'review_note'}=? WHERE tenant_id=? AND student_id=? AND id=? AND version=?`,b.state,body,a.tenant_id,id,taskId,b.version);this.s.audit(a,'task.'+b.state,taskId);return {id:taskId,state:b.state,version:b.version+1};});}
 createSession(a:Actor,id:string,b:any){this.staff(a,id);keys(b,['clientId','title','startsAt','endsAt']);check(uuid(b.clientId));const start=new Date(b.startsAt),end=new Date(b.endsAt);check(Number.isFinite(start.getTime())&&Number.isFinite(end.getTime())&&start<end&&end.getTime()-start.getTime()<=8*3600000&&start.getUTCFullYear()>=2020);const data={title:str(b.title),startsAt:start.toISOString(),endsAt:end.toISOString()},fingerprint=sha(JSON.stringify({student:id,...data}));return this.s.tx(()=>{const old=this.replay('study_sessions',a,b.clientId,fingerprint);if(old)return old;check(!this.s.one('SELECT id FROM study_sessions WHERE tenant_id=? AND student_id=? AND starts_at<? AND ends_at>?',a.tenant_id,id,data.endsAt,data.startsAt),409,'SESSION_OVERLAP');const key=randomUUID();this.s.run('INSERT INTO study_sessions(id,tenant_id,student_id,actor_id,client_id,fingerprint,title,starts_at,ends_at) VALUES(?,?,?,?,?,?,?,?,?)',key,a.tenant_id,id,a.id,b.clientId,fingerprint,data.title,data.startsAt,data.endsAt);this.s.audit(a,'session.planned',key);return {id:key,replayed:false};});}
 attendance(a:Actor,id:string,sessionId:string,b:any){this.staff(a,id);keys(b,['version','state']);num(b.version,1,2147483647);check(['present','absent','excused'].includes(b.state));return this.s.tx(()=>{const s=this.s.one('SELECT version,starts_at,ends_at FROM study_sessions WHERE tenant_id=? AND student_id=? AND id=?',a.tenant_id,id,sessionId);check(s,404,'NOT_FOUND');check(s.version===b.version,409,'VERSION_CONFLICT');if(b.state!=='excused')check(Date.now()>=new Date(b.state==='absent'?s.ends_at:s.starts_at).getTime(),422,'SESSION_NOT_STARTED');this.s.run('UPDATE study_sessions SET state=?,version=version+1 WHERE tenant_id=? AND student_id=? AND id=?',b.state,a.tenant_id,id,sessionId);this.s.audit(a,'attendance.'+b.state,sessionId);return {id:sessionId,state:b.state,version:b.version+1};});}
}
export function seedAcademics(service:Academics,store:Store,ids:any){const a=store.one('SELECT id,tenant_id,role,name FROM users WHERE id=?',ids['cizre-demo:ogretmen']),id=ids['cizre-demo:ogrenci:student'];const scores=[[[24,10],[17,12],[12,5],[10,6]],[[26,8],[20,10],[13,4],[11,5]],[[27,7],[21,9],[14,4],[12,4]],[[28,7],[23,8],[15,3],[13,4]],[[31,5],[25,7],[16,2],[14,3]]];scores.forEach((values,i)=>{const d=new Date(Date.now()-(29-i*7)*86400000);service.exam(a,id,{clientId:randomUUID(),title:'TYT Genel Deneme '+String(i+1).padStart(2,'0'),type:'TYT',day:day(d),subjects:Object.entries(templates.TYT).map(([name,q],j)=>({name,correct:values[j][0],wrong:values[j][1],blank:q-values[j][0]-values[j][1],divisor:4}))});});service.createTask(a,id,{clientId:randomUUID(),title:'Problemlerde yeni bir adım',subject:'Matematik',dueDay:day(new Date(Date.now()+2*86400000)),description:'Problemler testinden 30 soru çöz. Takıldığın soruları etüte getir.'});service.createTask(a,id,{clientId:randomUUID(),title:'Paragraf rutini',subject:'Türkçe',dueDay:day(new Date(Date.now()+4*86400000)),description:'20 paragraf sorusu ve yanlışlarının kısa özeti.'});const start=new Date(Date.now()+86400000);service.createSession(a,id,{clientId:randomUUID(),title:'Matematik · Soru çözümü',startsAt:start.toISOString(),endsAt:new Date(start.getTime()+3600000).toISOString()});}
