import {DatabaseSync} from 'node:sqlite';
import {randomUUID,randomBytes,createHash,scryptSync,timingSafeEqual} from 'node:crypto';
import {check,str,num,keys,day,uuid,classify,validateBatch} from './domain.ts';
import type {Actor} from './domain.ts';
export const sha=(s:string)=>createHash('sha256').update(s).digest('hex');
export function hash(s:string){const salt=randomBytes(16).toString('hex');return salt+':'+scryptSync(s,salt,64,{N:32768,r:8,p:1,maxmem:67108864}).toString('hex');}
function verify(s:string,h:string){const [salt,key]=h.split(':');const a=scryptSync(s,salt,64,{N:32768,r:8,p:1,maxmem:67108864}),b=Buffer.from(key,'hex');return a.length===b.length&&timingSafeEqual(a,b);}
export class Store{
 db:DatabaseSync;dummy:string;
 constructor(path=':memory:'){
  check(process.env.NODE_ENV!=='production',503,'DEVELOPMENT_ONLY');this.db=new DatabaseSync(path);this.dummy=hash(randomBytes(16).toString('hex'));
  this.db.exec(`PRAGMA foreign_keys=ON;PRAGMA journal_mode=WAL;PRAGMA busy_timeout=3000;
  CREATE TABLE IF NOT EXISTS tenants(id TEXT PRIMARY KEY,slug TEXT UNIQUE NOT NULL,name TEXT NOT NULL,telemetry INTEGER NOT NULL DEFAULT 0);
  CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL REFERENCES tenants(id),login TEXT NOT NULL,name TEXT NOT NULL,role TEXT NOT NULL CHECK(role IN ('admin','counselor','teacher','student')),password_hash TEXT NOT NULL,active INTEGER NOT NULL DEFAULT 1,UNIQUE(tenant_id,id),UNIQUE(tenant_id,login));
  CREATE TABLE IF NOT EXISTS students(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,user_id TEXT NOT NULL,name TEXT NOT NULL,class_name TEXT NOT NULL,status TEXT NOT NULL CHECK(status IN ('pending','active','suspended')),UNIQUE(tenant_id,id),UNIQUE(tenant_id,user_id),FOREIGN KEY(tenant_id,user_id) REFERENCES users(tenant_id,id));
  CREATE TABLE IF NOT EXISTS assignments(tenant_id TEXT NOT NULL,staff_id TEXT NOT NULL,student_id TEXT NOT NULL,PRIMARY KEY(tenant_id,staff_id,student_id),FOREIGN KEY(tenant_id,staff_id) REFERENCES users(tenant_id,id),FOREIGN KEY(tenant_id,student_id) REFERENCES students(tenant_id,id));
  CREATE TABLE IF NOT EXISTS sessions(token_hash TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id),csrf TEXT NOT NULL,expires INTEGER NOT NULL);
  CREATE TABLE IF NOT EXISTS consents(tenant_id TEXT NOT NULL,student_id TEXT NOT NULL,version INTEGER NOT NULL,enabled INTEGER NOT NULL,notice_version TEXT NOT NULL,granted_at TEXT NOT NULL,PRIMARY KEY(tenant_id,student_id),FOREIGN KEY(tenant_id,student_id) REFERENCES students(tenant_id,id));
  CREATE TABLE IF NOT EXISTS devices(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,student_id TEXT NOT NULL,installation_id TEXT NOT NULL,UNIQUE(tenant_id,id),UNIQUE(tenant_id,student_id,installation_id),FOREIGN KEY(tenant_id,student_id) REFERENCES students(tenant_id,id));
  CREATE TABLE IF NOT EXISTS batches(id TEXT NOT NULL,tenant_id TEXT NOT NULL,student_id TEXT NOT NULL,payload_hash TEXT NOT NULL,created_at TEXT NOT NULL,PRIMARY KEY(tenant_id,student_id,id),FOREIGN KEY(tenant_id,student_id) REFERENCES students(tenant_id,id));
  CREATE TABLE IF NOT EXISTS snapshots(tenant_id TEXT NOT NULL,student_id TEXT NOT NULL,device_id TEXT NOT NULL,day TEXT NOT NULL,revision INTEGER NOT NULL,window_start TEXT NOT NULL,window_end TEXT NOT NULL,quality TEXT NOT NULL,PRIMARY KEY(tenant_id,student_id,device_id,day),FOREIGN KEY(tenant_id,student_id) REFERENCES students(tenant_id,id),FOREIGN KEY(tenant_id,device_id) REFERENCES devices(tenant_id,id));
  CREATE TABLE IF NOT EXISTS usage(tenant_id TEXT NOT NULL,student_id TEXT NOT NULL,device_id TEXT NOT NULL,day TEXT NOT NULL,package TEXT NOT NULL,seconds INTEGER NOT NULL CHECK(seconds>0 AND seconds<=86400),PRIMARY KEY(tenant_id,student_id,device_id,day,package),FOREIGN KEY(tenant_id,student_id,device_id,day) REFERENCES snapshots(tenant_id,student_id,device_id,day) ON DELETE CASCADE);
  CREATE TABLE IF NOT EXISTS records(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,student_id TEXT NOT NULL,actor_id TEXT NOT NULL,client_id TEXT NOT NULL,kind TEXT NOT NULL,day TEXT NOT NULL,payload TEXT NOT NULL,payload_hash TEXT NOT NULL,source TEXT NOT NULL,created_at TEXT NOT NULL,UNIQUE(tenant_id,actor_id,client_id),FOREIGN KEY(tenant_id,student_id) REFERENCES students(tenant_id,id),FOREIGN KEY(tenant_id,actor_id) REFERENCES users(tenant_id,id));
  CREATE TABLE IF NOT EXISTS notes(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,student_id TEXT NOT NULL,body TEXT NOT NULL,created_at TEXT NOT NULL,FOREIGN KEY(tenant_id,student_id) REFERENCES students(tenant_id,id));
  CREATE TABLE IF NOT EXISTS audit(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,actor_id TEXT NOT NULL,action TEXT NOT NULL,subject TEXT NOT NULL,created_at TEXT NOT NULL,FOREIGN KEY(tenant_id,actor_id) REFERENCES users(tenant_id,id));
  CREATE INDEX IF NOT EXISTS records_history ON records(tenant_id,student_id,day);
  CREATE INDEX IF NOT EXISTS usage_history ON usage(tenant_id,student_id,day);`);
 }
 one(sql:string,...p:any[]):any{return this.db.prepare(sql).get(...p);}
 all(sql:string,...p:any[]):any[]{return this.db.prepare(sql).all(...p);}
 run(sql:string,...p:any[]){return this.db.prepare(sql).run(...p);}
 tx<T>(fn:()=>T):T{this.db.exec('BEGIN IMMEDIATE');try{const r=fn();this.db.exec('COMMIT');return r;}catch(e){this.db.exec('ROLLBACK');throw e;}}
 audit(a:Actor,action:string,subject:string){this.run('INSERT INTO audit VALUES(?,?,?,?,?,?)',randomUUID(),a.tenant_id,a.id,action,subject,new Date().toISOString());}
 login(tenant:string,login:string,password:string){const a=this.one('SELECT u.* FROM users u JOIN tenants t ON t.id=u.tenant_id WHERE t.slug=? AND u.login=?',tenant,login);const valid=verify(password,a?.password_hash??this.dummy);check(a&&a.active&&valid,401,'INVALID_CREDENTIALS');const token=randomBytes(32).toString('base64url'),csrf=randomBytes(24).toString('base64url');this.tx(()=>{this.run('DELETE FROM sessions WHERE expires<=?',Date.now());this.run('INSERT INTO sessions VALUES(?,?,?,?)',sha(token),a.id,csrf,Date.now()+28800000);this.audit(a,'session.created',a.id);});return {token,csrf};}
 session(token:string){const a=this.one('SELECT u.id,u.tenant_id,u.name,u.role,s.csrf FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires>? AND u.active=1',sha(token),Date.now());check(a,401,'UNAUTHENTICATED');return a as Actor&{csrf:string};}
 logout(token:string){this.run('DELETE FROM sessions WHERE token_hash=?',sha(token));}
 me(a:Actor){return {...a,tenant:this.one('SELECT name,telemetry FROM tenants WHERE id=?',a.tenant_id),student:this.one('SELECT id,status FROM students WHERE tenant_id=? AND user_id=?',a.tenant_id,a.id)??null};}
 own(a:Actor){check(a.role==='student',403,'STUDENT_ONLY');const s=this.one('SELECT * FROM students WHERE tenant_id=? AND user_id=? AND status=?',a.tenant_id,a.id,'active');check(s,403,'STUDENT_NOT_ACTIVE');return s;}
 authorize(a:Actor,id:string){const s=this.one('SELECT * FROM students WHERE tenant_id=? AND id=?',a.tenant_id,id);check(s,404,'NOT_FOUND');const assigned=this.one('SELECT 1 FROM assignments WHERE tenant_id=? AND staff_id=? AND student_id=?',a.tenant_id,a.id,id);check(a.role==='admin'||(a.role==='student'&&s.user_id===a.id)||(['counselor','teacher'].includes(a.role)&&assigned),404,'NOT_FOUND');check(s.status==='active'||a.role==='admin',403,'STUDENT_NOT_ACTIVE');return s;}
 list(a:Actor){return this.all('SELECT id,name,class_name,status,user_id FROM students WHERE tenant_id=? ORDER BY name',a.tenant_id).filter(s=>a.role==='admin'||(s.status==='active'&&(a.role==='student'?s.user_id===a.id:!!this.one('SELECT 1 FROM assignments WHERE tenant_id=? AND staff_id=? AND student_id=?',a.tenant_id,a.id,s.id)))).map(({user_id,...s})=>s);}
 consent(a:Actor,raw:any){const s=this.own(a);keys(raw,['enabled','noticeVersion']);check(typeof raw.enabled==='boolean');check(raw.noticeVersion==='2026-09-v1',422,'NOTICE_VERSION');const old=this.one('SELECT * FROM consents WHERE tenant_id=? AND student_id=?',a.tenant_id,s.id);return this.tx(()=>{const version=(old?.version??0)+1;this.run('INSERT INTO consents VALUES(?,?,?,?,?,?) ON CONFLICT(tenant_id,student_id) DO UPDATE SET version=excluded.version,enabled=excluded.enabled,notice_version=excluded.notice_version,granted_at=excluded.granted_at',a.tenant_id,s.id,version,raw.enabled?1:0,raw.noticeVersion,new Date().toISOString());if(!raw.enabled)this.run('DELETE FROM snapshots WHERE tenant_id=? AND student_id=?',a.tenant_id,s.id);this.audit(a,raw.enabled?'consent.granted':'consent.revoked',s.id);return {enabled:raw.enabled,version};});}
 consentState(a:Actor){const s=this.own(a);return this.one('SELECT version,enabled,notice_version,granted_at FROM consents WHERE tenant_id=? AND student_id=?',a.tenant_id,s.id)??{version:0,enabled:0};}
 device(a:Actor,installationId:unknown){const s=this.own(a);check(uuid(installationId));const old=this.one('SELECT id FROM devices WHERE tenant_id=? AND student_id=? AND installation_id=?',a.tenant_id,s.id,installationId);if(old)return old;const id=randomUUID();this.run('INSERT INTO devices VALUES(?,?,?,?)',id,a.tenant_id,s.id,installationId);return {id};}
 batch(a:Actor,raw:any){const s=this.own(a);check(this.one('SELECT telemetry FROM tenants WHERE id=?',a.tenant_id).telemetry===1,403,'FEATURE_DISABLED');const consent=this.consentState(a);check(consent.enabled===1,403,'CONSENT_REQUIRED');const b=validateBatch(raw);check(b.consentVersion===consent.version,409,'CONSENT_VERSION');check(new Date(b.windowStart)>=new Date(consent.granted_at),422,'BEFORE_CONSENT');check(this.one('SELECT id FROM devices WHERE tenant_id=? AND student_id=? AND id=?',a.tenant_id,s.id,b.deviceId),404,'DEVICE_NOT_FOUND');const payloadHash=sha(JSON.stringify(b));
 return this.tx(()=>{const old=this.one('SELECT payload_hash FROM batches WHERE tenant_id=? AND student_id=? AND id=?',a.tenant_id,s.id,b.batchId);if(old){check(old.payload_hash===payloadHash,409,'IDEMPOTENCY_CONFLICT');return {batchId:b.batchId,replayed:true};}const prev=this.one('SELECT * FROM snapshots WHERE tenant_id=? AND student_id=? AND device_id=? AND day=?',a.tenant_id,s.id,b.deviceId,b.day);if(prev){check(b.revision>prev.revision&&b.windowStart===prev.window_start&&b.windowEnd>=prev.window_end,409,'STALE_SNAPSHOT');}
 this.run('INSERT INTO snapshots VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(tenant_id,student_id,device_id,day) DO UPDATE SET revision=excluded.revision,window_start=excluded.window_start,window_end=excluded.window_end,quality=excluded.quality',a.tenant_id,s.id,b.deviceId,b.day,b.revision,b.windowStart,b.windowEnd,b.quality);this.run('DELETE FROM usage WHERE tenant_id=? AND student_id=? AND device_id=? AND day=?',a.tenant_id,s.id,b.deviceId,b.day);for(const app of b.apps)this.run('INSERT INTO usage VALUES(?,?,?,?,?,?)',a.tenant_id,s.id,b.deviceId,b.day,app.packageName,app.seconds);this.run('INSERT INTO batches VALUES(?,?,?,?,?)',b.batchId,a.tenant_id,s.id,payloadHash,new Date().toISOString());this.audit(a,'usage.synced',b.deviceId);return {batchId:b.batchId,replayed:false};});}
 profile(a:Actor,id:string){const s=this.authorize(a,id);const canUsage=['counselor','student'].includes(a.role);const usage=canUsage?this.all('SELECT device_id,day,package,seconds FROM usage WHERE tenant_id=? AND student_id=? ORDER BY day DESC,seconds DESC,package LIMIT 2000',a.tenant_id,id).map(r=>({...r,...classify(r.package)})):[];const records=this.all('SELECT id,kind,day,payload,source FROM records WHERE tenant_id=? AND student_id=? ORDER BY day DESC,created_at DESC LIMIT 300',a.tenant_id,id).filter(r=>r.kind!=='checkin'||canUsage).map(r=>({...r,payload:JSON.parse(r.payload)}));const notes=a.role==='counselor'?this.all('SELECT id,body,created_at FROM notes WHERE tenant_id=? AND student_id=? ORDER BY created_at DESC LIMIT 50',a.tenant_id,id):[];const snapshots=canUsage?this.all('SELECT device_id,day,quality,window_start,window_end FROM snapshots WHERE tenant_id=? AND student_id=? ORDER BY day DESC LIMIT 100',a.tenant_id,id):[];this.audit(a,'profile.read',id);return {student:{id:s.id,name:s.name,class_name:s.class_name,status:s.status},usage,snapshots,records,notes,canUsage,consent:canUsage?(this.one('SELECT enabled,version FROM consents WHERE tenant_id=? AND student_id=?',a.tenant_id,id)??{enabled:0,version:0}):null,limits:{usage:2000,records:300,notes:50}};}
 record(a:Actor,id:string,b:any){this.authorize(a,id);keys(b,['clientRecordId','kind','day','payload']);check(uuid(b.clientRecordId));check((a.role==='student'?['study','questions','checkin']:a.role==='teacher'?['exam','homework','attendance']:[]).includes(b.kind),403,'FORBIDDEN_KIND');check(typeof b.day==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(b.day)&&b.day<=day()&&b.day>='2020-01-01'&&Number.isFinite(new Date(b.day+'T12:00:00Z').getTime())&&new Date(b.day+'T12:00:00Z').toISOString().slice(0,10)===b.day);const p=b.payload;let payload:any;
 if(['study','questions'].includes(b.kind)){keys(p,['subject','value']);payload={subject:str(p.subject,60),value:num(p.value,1,b.kind==='study'?720:2000)};}
 else if(b.kind==='exam'){keys(p,['title','correct','wrong','blank','divisor']);const correct=num(p.correct,0,200),wrong=num(p.wrong,0,200),blank=num(p.blank,0,200),divisor=num(p.divisor,1,10);check(correct+wrong+blank>0&&correct+wrong+blank<=200);payload={title:str(p.title),correct,wrong,blank,divisor,net:Math.round((correct-wrong/divisor)*100)/100};}
 else{keys(p,['state','title']);const states=b.kind==='checkin'?['completed','partial','not_started','prefer_not_to_say']:b.kind==='attendance'?['present','absent','excused']:['assigned','verified'];check(states.includes(p.state));payload={state:p.state,...(b.kind==='checkin'?{}:{title:str(p.title)})};}
 const fingerprint=sha(JSON.stringify({student:id,kind:b.kind,day:b.day,payload}));return this.tx(()=>{const old=this.one('SELECT id,payload_hash FROM records WHERE tenant_id=? AND actor_id=? AND client_id=?',a.tenant_id,a.id,b.clientRecordId);if(old){check(old.payload_hash===fingerprint,409,'IDEMPOTENCY_CONFLICT');return {id:old.id,replayed:true};}if(b.kind==='study'){const sum=this.all('SELECT payload FROM records WHERE tenant_id=? AND student_id=? AND kind=? AND day=?',a.tenant_id,id,'study',b.day).reduce((n,r)=>n+JSON.parse(r.payload).value,0);check(sum+payload.value<=1440,422,'DAILY_MINUTES_LIMIT');}if(b.kind==='checkin')check(!this.one('SELECT id FROM records WHERE tenant_id=? AND student_id=? AND kind=? AND day=?',a.tenant_id,id,b.kind,b.day),409,'DAILY_CHECKIN_EXISTS');const key=randomUUID();this.run('INSERT INTO records VALUES(?,?,?,?,?,?,?,?,?,?,?)',key,a.tenant_id,id,a.id,b.clientRecordId,b.kind,b.day,JSON.stringify(payload),fingerprint,a.role==='student'?'Öğrenci beyanı':'Öğretmen girişi',new Date().toISOString());this.audit(a,'record.created',key);return {id:key,replayed:false};});}
 note(a:Actor,id:string,body:unknown){this.authorize(a,id);check(a.role==='counselor',403,'FORBIDDEN');const b=str(body,2000);return this.tx(()=>{const key=randomUUID();this.run('INSERT INTO notes VALUES(?,?,?,?,?)',key,a.tenant_id,id,b,new Date().toISOString());this.audit(a,'note.created',key);return {id:key};});}
 approve(a:Actor,id:string){check(a.role==='admin',403,'FORBIDDEN');const s=this.authorize(a,id);check(s.status==='pending',409,'INVALID_TRANSITION');return this.tx(()=>{this.run('UPDATE students SET status=? WHERE tenant_id=? AND id=?','active',a.tenant_id,id);this.audit(a,'student.approved',id);return {status:'active'};});}
 close(){this.db.close();}
}
export function seed(s:Store,password=randomBytes(18).toString('base64url')){
 check(!s.one('SELECT id FROM tenants LIMIT 1'),409,'DATABASE_NOT_EMPTY');const ids:any={},credentials:any[]=[];const h=hash(password);
 s.tx(()=>{for(const [t,slug,name]of[['tenant-a','cizre-demo','Cizre Örnek Akademi'],['tenant-b','diger-demo','İkinci Örnek Kurum']]){s.run('INSERT INTO tenants VALUES(?,?,?,1)',t,slug,name);for(const [role,login,name]of[['admin','admin','Demo Yönetici'],['counselor','rehberlik','Demo Rehberlik'],['teacher','ogretmen','Demo Öğretmen'],['student','ogrenci','Örnek Ada'],['student','ogrenci2','Örnek Deniz'],['student','bekleyen','Örnek Ekin']]){const id=randomUUID();ids[slug+':'+login]=id;s.run('INSERT INTO users VALUES(?,?,?,?,?,?,1)',id,t,login,name,role,h);credentials.push({tenant:slug,login,password,role});if(role==='student'){const sid=randomUUID();ids[slug+':'+login+':student']=sid;s.run('INSERT INTO students VALUES(?,?,?,?,?,?)',sid,t,id,name,'12 / A',login==='bekleyen'?'pending':'active');}}
 for(const who of['rehberlik','ogretmen'])s.run('INSERT INTO assignments VALUES(?,?,?)',t,ids[slug+':'+who],ids[slug+':ogrenci:student']);}});
 const a=s.one('SELECT * FROM users WHERE id=?',ids['cizre-demo:ogrenci']);const sid=ids['cizre-demo:ogrenci:student'];
 for(let i=0;i<4;i++){const d=new Date();d.setDate(d.getDate()-i);for(const kind of['study','questions'])s.record(a,sid,{clientRecordId:randomUUID(),kind,day:day(d),payload:{subject:'Matematik',value:kind==='study'?75+i*15:40+i*5}});}
 s.consent(a,{enabled:true,noticeVersion:'2026-09-v1'});const date=new Date();date.setDate(date.getDate()-1);const d=day(date),start=new Date(d+'T00:00:00+03:00').toISOString(),end=new Date(d+'T23:59:59+03:00').toISOString();s.run('UPDATE consents SET granted_at=? WHERE tenant_id=? AND student_id=?',start,a.tenant_id,sid);const dev=s.device(a,randomUUID());ids.device=dev.id;
 s.batch(a,{batchId:randomUUID(),deviceId:dev.id,consentVersion:1,day:d,revision:1,windowStart:start,windowEnd:end,timezone:'Europe/Istanbul',quality:'limited',apps:[{packageName:'com.google.android.youtube',seconds:4920},{packageName:'com.instagram.android',seconds:2580},{packageName:'com.whatsapp',seconds:1560},{packageName:'org.khanacademy.android',seconds:1200}]});return {credentials,ids};
}
