-- Additive Supabase foundation. Auth + membership provisioning is server-admin only.
begin;
create schema if not exists private;
revoke all on schema private from public;
create table public.school_tenants(id uuid primary key default gen_random_uuid(),name text not null);
create table public.school_memberships(tenant_id uuid references public.school_tenants not null,user_id uuid references auth.users not null,role text not null check(role in ('admin','teacher','counselor','student')),active boolean not null default true,primary key(tenant_id,user_id));
create table public.school_students(tenant_id uuid not null,id uuid not null default gen_random_uuid(),user_id uuid not null,name text not null,class_name text not null,status text not null check(status in ('pending','active','suspended')),primary key(tenant_id,id),unique(tenant_id,user_id),foreign key(tenant_id,user_id) references public.school_memberships(tenant_id,user_id));
create table public.school_assignments(tenant_id uuid not null,student_id uuid not null,staff_id uuid not null,primary key(tenant_id,student_id,staff_id),foreign key(tenant_id,student_id) references public.school_students,foreign key(tenant_id,staff_id) references public.school_memberships);
create function private.school_role(t uuid) returns text language sql stable security definer set search_path='' as $$select m.role from public.school_memberships m where m.tenant_id=t and m.user_id=(select auth.uid()) and m.active$$;
create function private.school_access(t uuid,s uuid,sensitive boolean default false) returns boolean language sql stable security definer set search_path='' as $$
 select exists(select 1 from public.school_students x join public.school_memberships m on m.tenant_id=x.tenant_id where x.tenant_id=t and x.id=s and m.user_id=(select auth.uid()) and m.active and ((m.role='admin' and not sensitive) or (x.status='active' and ((m.role='student' and x.user_id=m.user_id) or (m.role in ('teacher','counselor') and (not sensitive or m.role='counselor') and exists(select 1 from public.school_assignments a where a.tenant_id=t and a.student_id=s and a.staff_id=m.user_id))))))
$$;
revoke all on function private.school_role(uuid),private.school_access(uuid,uuid,boolean) from public;
grant usage on schema private to authenticated;
grant execute on function private.school_role(uuid),private.school_access(uuid,uuid,boolean) to authenticated;
create table public.school_exams(tenant_id uuid not null,student_id uuid not null,id uuid not null default gen_random_uuid(),created_by uuid not null,client_id uuid not null,title text not null,type text not null check(type in ('TYT','AYT')),day date not null,created_at timestamptz not null default now(),primary key(tenant_id,student_id,id),unique(tenant_id,created_by,client_id),foreign key(tenant_id,student_id) references public.school_students,foreign key(tenant_id,created_by) references public.school_memberships);
create table public.school_exam_subjects(tenant_id uuid not null,student_id uuid not null,exam_id uuid not null,name text not null,question_count integer not null check(question_count between 1 and 80),correct integer not null check(correct>=0),wrong integer not null check(wrong>=0),blank integer not null check(blank>=0),divisor integer not null check(divisor between 1 and 10),net numeric generated always as(round(correct::numeric-wrong::numeric/divisor,2)) stored,primary key(tenant_id,student_id,exam_id,name),foreign key(tenant_id,student_id,exam_id) references public.school_exams on delete cascade,check(correct+wrong+blank=question_count));
create table public.school_homework(tenant_id uuid not null,student_id uuid not null,id uuid not null default gen_random_uuid(),title text not null,subject text not null,due_day date not null,description text not null,state text not null default 'assigned' check(state in ('assigned','submitted','verified','needs_revision')),version integer not null default 1 check(version>0),student_note text not null default '',review_note text not null default '',primary key(tenant_id,student_id,id),foreign key(tenant_id,student_id) references public.school_students);
create table public.school_sessions(tenant_id uuid not null,student_id uuid not null,id uuid not null default gen_random_uuid(),title text not null,starts_at timestamptz not null,ends_at timestamptz not null,state text not null default 'planned' check(state in ('planned','present','absent','excused')),version integer not null default 1,primary key(tenant_id,student_id,id),foreign key(tenant_id,student_id) references public.school_students,check(ends_at>starts_at and ends_at<=starts_at+interval '8 hours'));
create table public.school_consents(tenant_id uuid not null,student_id uuid not null,version integer not null check(version>0),enabled boolean not null,notice_version text not null,granted_at timestamptz not null,primary key(tenant_id,student_id),foreign key(tenant_id,student_id) references public.school_students);
create table public.school_devices(tenant_id uuid not null,student_id uuid not null,id uuid not null default gen_random_uuid(),installation_id uuid not null,primary key(tenant_id,student_id,id),unique(tenant_id,student_id,installation_id),foreign key(tenant_id,student_id) references public.school_students);
create table public.school_usage_snapshots(tenant_id uuid not null,student_id uuid not null,device_id uuid not null,day date not null,revision integer not null check(revision>0),consent_version integer not null,window_start timestamptz not null,window_end timestamptz not null,quality text not null check(quality in ('partial','limited','complete')),primary key(tenant_id,student_id,device_id,day),foreign key(tenant_id,student_id,device_id) references public.school_devices,check(window_end>window_start and window_end<=window_start+interval '24 hours'));
create table public.school_usage_apps(tenant_id uuid not null,student_id uuid not null,device_id uuid not null,day date not null,package text not null,seconds integer not null check(seconds between 1 and 86400),primary key(tenant_id,student_id,device_id,day,package),foreign key(tenant_id,student_id,device_id,day) references public.school_usage_snapshots on delete cascade);
create table public.school_notes(tenant_id uuid not null,student_id uuid not null,id uuid not null default gen_random_uuid(),body text not null,created_at timestamptz not null default now(),primary key(tenant_id,student_id,id),foreign key(tenant_id,student_id) references public.school_students);
create table public.school_audit(tenant_id uuid not null references public.school_tenants,id uuid primary key default gen_random_uuid(),actor_id uuid not null references auth.users,action text not null,subject_id uuid not null,created_at timestamptz not null default now());
-- Client access is read-only here. Writes remain unavailable until transactional
-- Supabase runtime RPCs implement the tested Node domain contracts. Never expose service keys.
do $$declare t text;begin foreach t in array array['school_tenants','school_memberships','school_students','school_assignments','school_exams','school_exam_subjects','school_homework','school_sessions','school_consents','school_devices','school_usage_snapshots','school_usage_apps','school_notes','school_audit'] loop execute format('alter table public.%I enable row level security',t);execute format('revoke all on public.%I from anon,authenticated',t);execute format('grant select on public.%I to authenticated',t);end loop;end$$;
create policy tenant_read on public.school_tenants for select to authenticated using(private.school_role(id) is not null);
create policy membership_self on public.school_memberships for select to authenticated using(user_id=(select auth.uid()) and active);
create policy student_scope on public.school_students for select to authenticated using(private.school_access(tenant_id,id,false));
create policy assignment_self on public.school_assignments for select to authenticated using(staff_id=(select auth.uid()) and private.school_access(tenant_id,student_id,false));
do $$declare t text;begin foreach t in array array['school_exams','school_exam_subjects','school_homework','school_sessions'] loop execute format('create policy academic_scope on public.%I for select to authenticated using(private.school_access(tenant_id,student_id,false))',t);end loop;foreach t in array array['school_consents','school_devices','school_usage_snapshots','school_usage_apps'] loop execute format('create policy usage_scope on public.%I for select to authenticated using(private.school_access(tenant_id,student_id,true))',t);end loop;end$$;
create policy counselor_notes on public.school_notes for select to authenticated using(private.school_role(tenant_id)='counselor' and private.school_access(tenant_id,student_id,true));
create policy admin_audit on public.school_audit for select to authenticated using(private.school_role(tenant_id)='admin');
create index school_assignments_staff on public.school_assignments(tenant_id,staff_id,student_id);
create index school_students_user on public.school_students(user_id,tenant_id);
commit;
